algoritmo "6.0 Definir uma condição aos dados"
var
   // Variaveis globais //
   A, B, C: Inteiro
inicio
   // Comandos //
   Escreval ("Exemplo ()")
   Escreval ("")

   // Definir o valor da variavel //
   Escreva ("Digite um valor: ")
   Leia (A)
   Escreva ("Digite um valor: ")
   Leia (B)
   Escreva ("Digite um valor: ")
   Leia (C)

   // Definir a condição da variavel //
   Se entao
   Senão
   Fimse
fimalgoritmo